"""add trace_id to tickets

Revision ID: 76cfd790d8da
Revises: 35f5e58b4acc
Create Date: 2026-08-24 11:48:30.269642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cfd790d8da'
down_revision: Union[str, Sequence[str], None] = '35f5e58b4acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('trace_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'trace_id')
    # ### end Alembic commands ###
